### ISSUE TITLE
Connector is not compatible with AnyLogic 8.7.12

### ISSUE THREAD

**Issue by KMD2** [BonsaiAI/bonsai-anylogic#18]
Hello,

I have updated the AnyLogic software to 8.7.12, and it seems that the connecter needs to be updated as well. I tried downgrading AnyLogic to 8.7.11 but I couldn't open my models because they were saved by the newer version. I tried to edit the .alp file and change the model number as a temporary fix, but it didn't work out for me.

**Comment by t-wolfeadam** [comment]
I'm currently on 8.7.12 with the latest connector (v1.1.0) and have no issue registering a sim with bonsai, so I'm not sure it's an issue with the connector. 

Can you elaborate on what error messages you're receiving? And any information about the model? If you could include it as well that would be helpful.

**Comment by KMD2** [comment]
I am able to successfully connect the brain locally, but once I upload it for training, it seems that there is a problem connecting to the simulation, as I have noticed from the logs, when the training starts, the brain keeps on sending the configurations over and over (episodes ends right away).  Below is part of the log, if you notice, the episode is finished and the reason was "Interrupted".

`Jun 03, 2022 6:48:27 PM com.anylogic.rl.connector.bonsai.SimulatorSession getNextEvent
INFO: {"type":"EpisodeFinish","sessionId":"233888336_10.244.13.240","sequenceId":227,"episodeStart":null,"episodeStep":null,"episodeFinish":{"reason":"Interrupted"},"idle":null,"unregister":null}
Jun 03, 2022 6:48:27 PM com.anylogic.rl.connector.bonsai.SimulatorSession getNextEvent
INFO: {"sessionId":"233888336_10.244.13.240","sequenceId":227,"halted":false,"state":{"currentTime":0.0,"supplyDemandGapRegion1":0,"supplyDemandGapRegion2":0,"invalidActionReposition":0,"invalidActionWaiting":0,"distance":0.0,"possibleActions":null}}
Jun 03, 2022 6:48:27 PM com.anylogic.rl.connector.bonsai.SimulatorSession getNextEvent
INFO: calling: https://prodkube-api.azint.bons.ai/v2/workspaces/de7ef687-cb3e-49ab-aaf1-21d20c8997e0/simulatorSessions/233888336_10.244.13.240/advance
Jun 03, 2022 6:48:29 PM com.anylogic.rl.connector.bonsai.SimulatorSession getNextEvent
INFO: {"type":"EpisodeStart","sessionId":"233888336_10.244.13.240","sequenceId":228,"episodeStart":{"config":{"co2PerKmEmpty":0.800000011920929,"rate":1,"consumptionPerKmLoaded":0.41200000047683716,"co2PerKmLoaded":1.0850000381469727,"consumptionPerKmEmpty":0.3059999942779541}},"episodeStep":null,"episodeFinish":null,"idle":null,"unregister":null}` 

I have tried to verify this with a simulation that was used to successfully train a brain before. I saved the simulation with the latest AnyLogic version and uploaded it for training, I observed the same behavior.

If sharing the model would help in this case, would you mind sharing an email address so I can send it privately?.

Thank you.

**Comment by KMD2** [comment]
UPDATE: Looking more into it, it seems that it has nothing to do with the AnyLogic update, I have tried uploading old models that were previously trained but I am still facing the same issue, the simulator keeps on connecting and disconnecting and never starts training.

**Comment by davidhcoe** [comment]
I see several errors associated with your workspace. I will investigate with the team.

**Comment by davidhcoe** [comment]
It looks like a number of errors are related to your inkling code. I see 107k+ errors that state:

 An unexpected error occurred when running inkling code. Attempt to access an unknown member "possibleActions". Known fields include ['currentTime', 'supplyDemandGapRegion1', 'supplyDemandGapRegion2', 'invalidActionReposition', 'invalidActionWaiting', 'distance', '_schema_possibleActions_5B0_5D', '_schema_possibleActions_5B1_5D', '_schema_possibleActions_5B2_5D', '_schema_possibleActions_5B3_5D', '__..mem..__'].

There are several others related to state validation of your inkling:

State validation failed for state:

Fields: [SchemaField(name=currentTime), SchemaField(name=supplyDemandGapRegion1), SchemaField(name=supplyDemandGapRegion2), SchemaField(name=invalidActionOrder), SchemaField(name=invalidActionReposition), SchemaField(name=invalidActionWaiting), SchemaField(name=distance), SchemaField(name=repositioningCost), SchemaField(name=_schema_possibleActions_5B0_5D), SchemaField(name=_schema_possibleActions_5B1_5D), SchemaField(name=_schema_possibleActions_5B2_5D), SchemaField(name=_schema_possibleActions_5B3_5D)]

Flattened: OrderedDict([('invalidActionWaiting', -1.0), ('supplyDemandGapRegion2', -2.0), ('distance', 0.0), ('supplyDemandGapRegion1', -1.0), ('possibleActions[0]', 1.0), ('possibleActions[1]', -1.0), ('possibleActions[2]', -1.0), ('possibleActions[3]', 4.0), ('currentTime', 5.0), ('invalidActionReposition', -1.0)])

Prev State: None

Prev Action: None

Missing fields: ['invalidActionOrder', 'repositioningCost']

**Comment by KMD2** [comment]
That is strange, as I am not getting any errors displayed when trying to train the brain. possibleActions is an array of valid action values I have in the simulation as well as the Inkling code used for action masking.

I suspect the issue might be from using action masking, although we have been using it for a month now. I just uploaded an older model without the use of action masking and it started training normally.

As for the missing fields, this might have been an error we encountered earlier and took care of.

**Comment by davidhcoe** [comment]
I only have your workspace right now. If you provide your brain name and version I can look into specifics of that brain.

There is a feature in the UI called "Report an Issue" (It looks like a little bug). This will generate a report that you can email to bonsaiQ@microsoft.com. I will be one of the recipients and can look into it more.
